services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: resource-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
